server:
  error:
    include-stacktrace: on_param
##?trace=true habilita o stacktrace
  port: 8090
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
